#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_ESB=y
CONFIG_DK_LIBRARY=y
CONFIG_CLOCK_CONTROL=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=252

# Gdb related configs
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_THREAD_INFO=y

# gcc setting
CONFIG_DEBUG_OPTIMIZATIONS=y

CONFIG_I2C=y
CONFIG_I2S=y

CONFIG_AUDIO=y
CONFIG_AUDIO_CODEC=y
CONFIG_USE_CODEC_CLOCK=y
CONFIG_SAMPLE_FREQ=48000
CONFIG_I2S_INIT_BUFFERS=4
CONFIG_EXTRA_BLOCKS=0

CONFIG_MAIN_STACK_SIZE=10240

CONFIG_AUDIO_CODEC_LOG_LEVEL_DBG=y
CONFIG_FPU=y
